### ISSUE TITLE
What is the use case for this?

### ISSUE THREAD

**Issue by weoreference** [rahatarmanahmed/genetic-phrase-solver#1]
Hello, this seems very interesting.

I do notice that you are supplying the solver with the answer ('Hello World') before having it generate that very answer ('Hello World')... seems a bit circular.

I wonder if you could demonstrate a more real-world yet still simple scenario with this module of yours.

Thanks a lot.

I'm just curious, that's all.

**Comment by rahatarmanahmed** [comment]
Heh, there's not really a real-world use case for this. I used it as a demonstration of how a genetic algorithm would work in this digital essay I wrote: http://rahatah.me/pierre-monard/

I did write [evolutionary](https://www.npmjs.com/package/evolutionary), which this module depends on. That might be useful as a generic genetic algorithm library, but I wouldn't really know if its a particularly good implementation. I was mostly exploring how genetic algorithms worked.

**Comment by rahatarmanahmed** [comment]
May I ask how you found this repository?
